import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import {
  IonApp,
  IonContent,
  IonHeader,
  IonIcon,
  IonItem,
  IonLabel,
  IonList,
  IonMenu,
  IonMenuToggle,
  IonRouterLink,
  IonRouterOutlet,
  IonSplitPane,
  IonTitle,
  IonToolbar,
} from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  accessibility,
  add,
  addCircle,
  airplane,
  alarm,
  albums,
  alert,
  alertCircle,
  analytics,
  archive,
  at,
  baseball,
  basket,
  batteryCharging,
  beer,
  bicycle,
  boat,
  bookmarks,
  browsers,
  calendar,
  checkbox,
  chevronBack,
  chevronForward,
  close,
  closeCircle,
  copy,
  eye,
  eyeOff,
  fingerPrint,
  grid,
  heart,
  home,
  infinite,
  informationCircle,
  list,
  lockClosed,
  lockOpen,
  logoAndroid,
  logoAngular,
  logoApple,
  logoBitcoin,
  logoFacebook,
  logoGithub,
  logoInstagram,
  logoNodejs,
  logoSteam,
  logoTux,
  logoTwitter,
  logoVimeo,
  logoYoutube,
  menu,
  musicalNote,
  notifications,
  people,
  personAdd,
  pin,
  playCircle,
  refresh,
  refreshCircle,
  remove,
  reorderFour,
  reorderThree,
  search,
  share,
  square,
  star,
  swapHorizontal,
  trash,
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
  imports: [
    RouterLink,
    RouterLinkActive,
    IonApp,
    IonSplitPane,
    IonMenu,
    IonContent,
    IonList,
    IonMenuToggle,
    IonItem,
    IonIcon,
    IonLabel,
    IonRouterLink,
    IonRouterOutlet,
    IonHeader,
    IonToolbar,
    IonTitle,
  ],
})
export class AppComponent {
  public appPages = [
    { title: 'Action sheet', url: '/action-sheet', icon: 'menu' },
    { title: 'Alert', url: '/alert', icon: 'alert-circle' },
    { title: 'Badges & Chips', url: '/badges', icon: 'notifications' },
    { title: 'Buttons', url: '/buttons', icon: 'square' },
    { title: 'Cards', url: '/cards', icon: 'albums' },
    { title: 'Forms', url: '/forms', icon: 'checkbox' },
    { title: 'Grid', url: '/grid', icon: 'grid' },
    { title: 'Lists', url: '/lists', icon: 'list' },
    { title: 'Loading', url: '/loading', icon: 'refresh' },
    { title: 'Popover', url: '/popover', icon: 'albums' },
    { title: 'Toolbars', url: '/toolbars', icon: 'browsers' },
    { title: 'Toast', url: '/toast', icon: 'alert' },
  ];
  constructor() {
    addIcons({
      square,
      star,
      logoGithub,
      list,
      chevronBack,
      chevronForward,
      accessibility,
      airplane,
      alarm,
      checkbox,
      lockClosed,
      lockOpen,
      eye,
      eyeOff,
      remove,
      reorderFour,
      grid,
      albums,
      pin,
      notifications,
      closeCircle,
      addCircle,
      add,
      share,
      logoFacebook,
      logoInstagram,
      logoTwitter,
      logoVimeo,
      logoYoutube,
      browsers,
      search,
      personAdd,
      refresh,
      alert,
      analytics,
      logoAngular,
      logoAndroid,
      logoApple,
      archive,
      at,
      baseball,
      basket,
      batteryCharging,
      beer,
      bicycle,
      logoBitcoin,
      boat,
      logoNodejs,
      logoTux,
      logoSteam,
      swapHorizontal,
      alertCircle,
      menu,
      trash,
      playCircle,
      heart,
      close,
      refreshCircle,
      infinite,
      reorderThree,
      bookmarks,
      fingerPrint,
      home,
      informationCircle,
      people,
      copy,
      musicalNote,
      calendar,
    });
  }
}
